name: Dump & Deploy data every 5 min

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dump-and-deploy:
    runs-on: ubuntu-latest
    env:
      # ✅ 여기에서 전체 스텝에 SA 인증 적용
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/nearby-sa.json
      FIREBASE_PROJECT_ID: nearby-data

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps & Firebase CLI
        run: |
          npm ci || npm i
          npm i -g firebase-tools jq

      - name: Write service accounts
        run: |
          echo '${{ secrets.CPK_SERVICE_ACCOUNT_JSON }}' > serviceAccountKey.json
          echo '${{ secrets.NEARBY_SERVICE_ACCOUNT_JSON }}' > nearby-sa.json

      - name: Debug SA project and hosting sites
        run: |
          echo "Service Account project_id:"; jq -r '.project_id' nearby-sa.json
          echo ""
          echo "Hosting sites in this project:"
          firebase hosting:sites:list --project "$FIREBASE_PROJECT_ID"

      - name: Run dump script
        run: |
          mkdir -p public/data
          npm run dump

      - name: Detect changes in public/data
        id: diff
        run: |
          if git diff --quiet -- public/data; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Safety check (ensure correct site)
        if: steps.diff.outputs.changed == 'true'
        run: |
          jq -e '.hosting.site == "nearby-data"' firebase.json >/dev/null
          echo "firebase.json points to hosting site 'nearby-data' ✅"

      - name: Deploy to Firebase Hosting
        if: steps.diff.outputs.changed == 'true'
        run: |
          firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --non-interactive
